# LMAPR1492 : Projet
## Partie 2 : Symétries des atomes de la molécules $Cs_2O$

In [1]:
import numpy as np
from mp_api.client import MPRester
from pymatgen.core.operations import SymmOp
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer
from jupyter_jsmol.pymatgen import quick_view

In [2]:
mp_key = "ClP8wE7rgC4VunNMMiut1b2BYMfgW6Lu"
mp_id = "mp-7988"

In [3]:
with MPRester(mp_key) as m:
    prim_struc = m.get_structure_by_material_id(mp_id)

conv_struc = SpacegroupAnalyzer(prim_struc).get_conventional_standard_structure()
symmops = SpacegroupAnalyzer(conv_struc).get_space_group_operations()

Retrieving MaterialsDoc documents:   0%|          | 0/1 [00:00<?, ?it/s]

### Première symétrie :

In [4]:
i_atom = 5
i_symmop = 5

symmop = symmops[i_symmop - 1]

pos_init = conv_struc.sites[i_atom -1].frac_coords

pos_final = symmop.operate(pos_init)


for k_atom, site in enumerate(conv_struc.sites):
    if np.linalg.norm((site.frac_coords - pos_final)%1) < 1e-6:
        j_atom = k_atom + 1

print("Pour le " + str(i_atom) + "e atome de la molécule (atome d'oxygène) , \n La "+str(i_symmop)+"e opération de symétrie est une rotation d'ordre 3 \n Qui peut être représentée par la matrice : ")
print(symmop)
print("\n La position initiale de l'atome est : ")
print(pos_init)
print("\n Sa position après l'opération de symétrie est : ")
print(pos_final)
print("\n Ce qui correspond au " + str(j_atom) + "e atome de la maille conventionnelle dont les coordonées sont :")
print(conv_struc.sites[j_atom -1].frac_coords)

view = quick_view(prim_struc, "packed", conventional = True)
display(view)

view.script('select oxygen; color red')
view.script('select caesium; color blue')
view.script('draw SYMOP ' + str(i_symmop) + ' {atomno = ' + str(i_atom) + '}')

Pour le 5e atome de la molécule (atome d'oxygène) , 
 La 5e opération de symétrie est une rotation d'ordre 3 
 Qui peut être représentée par la matrice : 
Rot:
[[-1.  1.  0.]
 [-1.  0.  0.]
 [ 0.  0.  1.]]
tau
[0. 0. 0.]

 La position initiale de l'atome est : 
[0.33333333 0.66666667 0.9245481 ]

 Sa position après l'opération de symétrie est : 
[ 0.33333333 -0.33333333  0.9245481 ]

 Ce qui correspond au 5e atome de la maille conventionnelle dont les coordonées sont :
[0.33333333 0.66666667 0.9245481 ]


JsmolView(layout=Layout(align_self='stretch', height='400px'))

### Deuxième symétrie

In [5]:
i_atom = 7
i_symmop = 32

symmop = symmops[i_symmop - 1]

pos_init = conv_struc.sites[i_atom -1].frac_coords

pos_final = symmop.operate(pos_init)

for k_atom, site in enumerate(conv_struc.sites):
    if np.linalg.norm((site.frac_coords - pos_final)%1) < 1e-6:
        j_atom = k_atom + 1

print("Pour le " + str(i_atom) + "e atome de la molécule (atome de césium), \n La "+str(i_symmop)+"e opération de symétrie est un plan de glissement \n Qui peut être représentée par la matrice : ")
print(symmop)
print("\n La position initiale de l'atome est : ")
print(pos_init)
print("\n Sa position après l'opération de symétrie est : ")
print(pos_final)
print("\n Ce qui correspond au " + str(j_atom) + "e atome de la maille conventionnelle dont les coordonées sont :")
print(conv_struc.sites[j_atom -1].frac_coords)

view = quick_view(prim_struc, "packed", conventional = True)
display(view)

view.script('select oxygen; color red')
view.script('select caesium; color blue')
view.script('draw SYMOP ' + str(i_symmop) + ' {atomno = ' + str(i_atom) + '}')

Pour le 7e atome de la molécule (atome de césium), 
 La 32e opération de symétrie est un plan de glissement 
 Qui peut être représentée par la matrice : 
Rot:
[[ 0. -1.  0.]
 [-1.  0.  0.]
 [ 0.  0.  1.]]
tau
[0.33333333 0.66666667 0.66666667]

 La position initiale de l'atome est : 
[0. 0. 0.]

 Sa position après l'opération de symétrie est : 
[0.33333333 0.66666667 0.66666667]

 Ce qui correspond au 9e atome de la maille conventionnelle dont les coordonées sont :
[0.33333333 0.66666667 0.66666667]


JsmolView(layout=Layout(align_self='stretch', height='400px'))

### Troisième symétrie

In [6]:
i_atom = 3
i_symmop = 13

symmop = symmops[i_symmop - 1]

pos_init = conv_struc.sites[i_atom -1].frac_coords

pos_final = symmop.operate(pos_init)


for k_atom, site in enumerate(conv_struc.sites):
    if np.linalg.norm((site.frac_coords - pos_final)%1) < 1e-6:
        j_atom = k_atom + 1

print("Pour le " + str(i_atom) + "e atome de la molécule (autre atome de césium), \n La "+str(i_symmop)+"e opération de symétrie est une translation \n Qui peut être représentée par la matrice : ")
print(symmop)
print("\n La position initiale de l'atome est : ")
print(pos_init)
print("\n Sa position après l'opération de symétrie est : ")
print(pos_final)
print("\n Ce qui correspond au " + str(j_atom) + "e atome de la maille conventionnelle dont les coordonées sont :")
print(conv_struc.sites[j_atom -1].frac_coords)

view = quick_view(prim_struc, "packed", conventional = True)
display(view)

view.script('select oxygen; color red')
view.script('select caesium; color blue')
view.script('draw SYMOP ' + str(i_symmop) + ' {atomno = ' + str(i_atom) + '}')

Pour le 3e atome de la molécule (autre atome de césium), 
 La 13e opération de symétrie est une translation 
 Qui peut être représentée par la matrice : 
Rot:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
tau
[0.66666667 0.33333333 0.33333333]

 La position initiale de l'atome est : 
[0.66666667 0.33333333 0.59121476]

 Sa position après l'opération de symétrie est : 
[1.33333333 0.66666667 0.9245481 ]

 Ce qui correspond au 5e atome de la maille conventionnelle dont les coordonées sont :
[0.33333333 0.66666667 0.9245481 ]


JsmolView(layout=Layout(align_self='stretch', height='400px'))